repos:
  # Autoformat: Python code
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        # args ref: https://github.com/PyCQA/autoflake#advanced-usage
        args:
          - --in-place

  # # Autoformat: Python code
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.13.2
  #   hooks:
  #     - id: isort

  # # Autoformat: Python code
  # - repo: https://github.com/psf/black
  #   rev: 23.12.1
  #   hooks:
  #     - id: black

  # # Autoformat: markdown, yaml, javascript (see the file .prettierignore)
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v3.1.0
  #   hooks:
  #     - id: prettier

  # # Autoformat and linting, misc. details
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.5.0
  #   hooks:
  #     - id: end-of-file-fixer
  #     - id: requirements-txt-fixer
  #     - id: check-case-conflict
  #     - id: check-executables-have-shebangs

  # Linting: Python code
  - repo: https://github.com/PyCQA/flake8
    rev: "6.1.0"
    hooks:
      - id: flake8
        args:
          - --extend-ignore=E501
